// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ZGsCvLFHpT7PtnZhE-faFo3wTky9f-k',
    appId: '1:421116596215:web:10f233a2b42c30a4b4e8f2',
    messagingSenderId: '421116596215',
    projectId: 'maturitagjjj',
    authDomain: 'maturitagjjj.firebaseapp.com',
    storageBucket: 'maturitagjjj.firebasestorage.app',
    measurementId: 'G-F8S7H7GVR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyoxCyRTqMaTYD5UCzB5hHJ_L8B1wTu-Y',
    appId: '1:421116596215:android:60a4afdc5a7e25f0b4e8f2',
    messagingSenderId: '421116596215',
    projectId: 'maturitagjjj',
    storageBucket: 'maturitagjjj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeK__P0SH-eRq_8o1kSmMOs9zar3TzwB0',
    appId: '1:421116596215:ios:a605626a750d1951b4e8f2',
    messagingSenderId: '421116596215',
    projectId: 'maturitagjjj',
    storageBucket: 'maturitagjjj.firebasestorage.app',
    iosBundleId: 'com.example.maturitagjjj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeK__P0SH-eRq_8o1kSmMOs9zar3TzwB0',
    appId: '1:421116596215:ios:a605626a750d1951b4e8f2',
    messagingSenderId: '421116596215',
    projectId: 'maturitagjjj',
    storageBucket: 'maturitagjjj.firebasestorage.app',
    iosBundleId: 'com.example.maturitagjjj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ZGsCvLFHpT7PtnZhE-faFo3wTky9f-k',
    appId: '1:421116596215:web:def75432147926b8b4e8f2',
    messagingSenderId: '421116596215',
    projectId: 'maturitagjjj',
    authDomain: 'maturitagjjj.firebaseapp.com',
    storageBucket: 'maturitagjjj.firebasestorage.app',
    measurementId: 'G-43PFF3J45X',
  );
}
